language: python
python:
  #- "2.7"
  - "3.4"
  #- "3.8"
sudo: false
install:
  - pip install codecov
  - pip install mock

script:
  # (Re)install library
  # This implicitly covers build
  - pip uninstall GSMTC35 --yes
  - python setup.py install
  # Launch test coverage
  - coverage run test/unittest.py

# Push the results back to codecov
after_success:
  - codecov
