language: python
python:
  #- "2.7"
  - "3.4"
  #- "3.8"
sudo: false
install:
  - pip install codecov
  - pip install mock

script:
  # (Re)install library
  # This implicitly covers build (and test coverage on setup.py)
  - pip uninstall GSMTC35 --yes
  - coverage run -p setup.py install
  # Launch library test (+ test coverage)
  - coverage run -p test/test.py
  # Prepare results before sending them back to codecov
  - coverage combine

# Push the results back to codecov
after_success:
  - codecov
